{
 "title": "MongoDB",
 "tags": [
  "ot-dashboard ",
  "ot-mongo_db"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoService ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_up{rems_application_group=\"$ApplicationGroup\", rems_service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Connection Usage & Capacity",
   "type": "stat",
   "description": "Shows current active MongoDB connections, rejected connection,available connection capacity.",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\",\r\n  conn_type=~\"active|available|current|rejected\"\r\n}",
     "legendFormat": "{{conn_type}} "
    }
   ]
  },
  {
   "title": "Total Objects (Documents)",
   "type": "stat",
   "description": "Tells how many documents or records are stored in the database.\n",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_objects{rems_application_group=\"$ApplicationGroup\",rems_service=\"$service\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "MongoDB Total Collections",
   "type": "stat",
   "description": "Shows the total number of collections present in each MongoDB database.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{rems_application_group=\"$ApplicationGroup\" , rems_service=\"$service\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Mongo db Data Size ",
   "type": "stat",
   "description": "Displays the total number of documents in each MongoDB database to track data growth and detect abnormal insert patterns.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_dataSize{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\"\r\n} / 1024 / 1024",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Operations & Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": " Total Operations",
   "type": "timeseries",
   "description": "Displays the rate of MongoDB database operations per second, including command, query, insert, update, and delete operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (legacy_op_type) (\r\n  rate(\r\n    mongodb_ss_opcounters{\r\n      rems_application_group=\"$ApplicationGroup\",\r\n      rems_service=\"$service\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "This graph specifically tracks the rate of document-level operations (inserts, queries, updates, deletes, getsmore, commands). This helps understand the intensity of CRUD (Create, Read, Update, Delete) activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (legacy_op_type) (\r\n  rate(\r\n    mongodb_ss_opcounters{\r\n      rems_application_group=\"$ApplicationGroup\",\r\n      rems_service=\"$service\",\r\n      legacy_op_type=~\"query|insert|update|delete\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Inbound Traffic",
   "type": "timeseries",
   "description": "Shows how much data is coming into the database.\nThis includes requests, queries, etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(\r\n  mongodb_ss_network_bytesIn{\r\n    rems_application_group=\"$ApplicationGroup\",\r\n    rems_service=\"$service\"\r\n  }[5m]\r\n)",
     "legendFormat": "I/O Received"
    },
    {}
   ]
  },
  {
   "title": "Network Outbound Traffic",
   "type": "timeseries",
   "description": "Shows how much data the database is sending out, like responses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(\r\n  mongodb_ss_network_bytesOut{\r\n    rems_application_group=\"$ApplicationGroup\",\r\n    rems_service=\"$service\"\r\n  }[5m]\r\n)",
     "legendFormat": "I/O transmit"
    }
   ]
  },
  {
   "title": " Network Requests ",
   "type": "timeseries",
   "description": "Displays how many total requests are hitting the database.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(\r\n  mongodb_ss_network_numRequests{\r\n    rems_application_group=\"$ApplicationGroup\",\r\n    rems_service=\"$service\"\r\n  }[$__interval]\r\n)",
     "legendFormat": "request_count"
    }
   ]
  },
  { "title": "Cursors & Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Active Cursors",
   "type": "timeseries",
   "description": "Displays the number of open cursors in MongoDB. High values may indicate long-running queries or inefficient data retrieval.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_open{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\"\r\n}",
     "legendFormat": "{{csr_type}}"
    }
   ]
  },
  {
   "title": "Cache Requested",
   "type": "timeseries",
   "description": "Displays the number of page requests made to the WiredTiger cache. These requests represent attempts by MongoDB to retrieve data from memory before accessing disk storage.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_wt_cache_pages_requested_from_the_cache {rems_application_group=\"$ApplicationGroup\" ,rems_service=\"$service\"}",
     "legendFormat": "requested_cache "
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Shows the rate of pages read from disk into the WiredTiger cache, indicating cache misses and disk access frequency.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_cache_pages_read_into_cache{rems_application_group=\"$ApplicationGroup\",rems_service=\"$service\"}[$__interval])",
     "legendFormat": "cache_hit_ratio"
    }
   ]
  },
  { "title": " Indexing & Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Total Index Size",
   "type": "stat",
   "description": "Shows how much space is used by indexes.\n",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_dbstats_indexSize{rems_application_group=\"$ApplicationGroup\", rems_service=\"$service\"}) /1024",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Indexes",
   "type": "stat",
   "description": " This panel shows the total number of indexes defined across all collections in all databases.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_dbstats_indexes{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\"\r\n})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "MongoDB Lock Queue",
   "type": "stat",
   "description": "Displays the number of read and write operations currently waiting for database locks. High values may indicate lock contention or heavy workload.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_ss_globalLock_currentQueue{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\"\r\n})",
     "legendFormat": "{{count_type}}"
    },
    {}
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Resident Memory ",
   "type": "stat",
   "description": "Amount of physical RAM currently used by the MongoDB process",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_memory{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\" ,\r\n   type=\"resident\"\r\n} /1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory ",
   "type": "stat",
   "description": "Total virtual memory allocated by MongoDB",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_memory{\r\n  rems_application_group=\"$ApplicationGroup\",\r\n  rems_service=\"$service\",\r\n  type=\"virtual\"\r\n} / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}